---
title: "TFM_E2_Grupo02"
output: html_document
date: "2023-06-08"
---
  
```{r}
library(dplyr)
library(factoextra)
library(ggplot2)
library(cluster)
library(tidyverse)
library(ggcorrplot)
library(writexl)
library(openxlsx)
library(PerformanceAnalytics)
library(corrplot)
```


```{r}
#cargamos los datos con las variables que nos interesan
#df1 = data.frame(read.csv2('C:/Users/linfante/OneDrive/Documentos/MasterBigData/TFM/tfm_master_ds/1 - BackEnd/Datos/alimentos v3.csv', sep=','))
#df2 = data.frame(read.csv2('C:/Users/linfante/OneDrive/Documentos/MasterBigData/TFM/tfm_master_ds/1 - BackEnd/Datos/alimentos_vegan.csv', sep=','))
df = data.frame(read.csv2('C:/Users/linfante/OneDrive/Documentos/MasterBigData/TFM/tfm_master_ds/1 - BackEnd/Datos/alimentos v4.csv', sep=','))

```


```{r}
#df <- df[,c("PRODUCT_NAME","PROTEINS_100G","CARBOHYDRATES_100G","FAT_100G","FIBER_100G","SALT_100G","SATURATED_FAT_100G","SUGARS_100G")]
df <- df[,c("PRODUCT_NAME","PROTEINS_100G","CARBOHYDRATES_100G","FAT_100G")]
```


```{r}
PRODUCT_NAME <- df[,1]
 
# Filtrar las columnas que contienen el texto "_100G"
#columnas_filtradas <- grep("_100G", colnames(df))
#df <- df[, columnas_filtradas]
#df <- cbind(PRODUCT_NAME,df)

#Convertir a numerico todo
df_nuevo <- df %>%
  mutate(across(where(is.character), type.convert, as.is = TRUE)) %>%
  select_if(is.numeric)

total <- as.data.frame(colSums(df_nuevo))
totalc <- as.data.frame(rowSums(df_nuevo))
```

```{r}
totales <- colSums(df_nuevo)

# Seleccionar las columnas con un total mayor o igual a 5
#columnas_a_mantener <- totales >= 10000

# Eliminar las columnas con un total inferior a 30
#df_nuevo <- df_nuevo[, columnas_a_mantener]
PRODUCT_NAME <- df[,1]
df_nuevo <- cbind(PRODUCT_NAME,df_nuevo)

```


```{r}
#elimina vectores fila nulos 
df_nuevo$suma <- rowSums(df_nuevo[, c("PROTEINS_100G","CARBOHYDRATES_100G","FAT_100G")])
df_nuevo <- subset(df_nuevo, !(suma == 0))
df_nuevo <- df_nuevo[,c("PRODUCT_NAME","PROTEINS_100G","CARBOHYDRATES_100G","FAT_100G")]
df_nuevo <- na.omit(df_nuevo)

```


```{r}
#filtros negativos
# Crear un vector con las palabras a buscar
palabras_a_eliminar <- c("SALSA DE SOJA","SAUCE SOJA", "SAUCE SOJA","BEBIDA DE SOJA", "YAOURT SOJA","YOGURT DE SOJA","CHOCOLAT","ARROZ Y SOJA","LECHE","MOUSSE","MILK","ACEITE","DESSERT","PAN SOJA","BOISSON SOJA", "GLACE","ML","SAUCE DE SOJA","SAUCE","SALSA","BIBEDA DE SOJA","LAIT SOJA","VIVESOY SOJA","LAIT DE SOJA","YAOURT","POSTRE","MUESLI","YOGUR","BEBIDA","MARGARINA","VINAIGRETTE","DRINK","SAUCE","BATIDO","LAIT","MAYONNAISE","CAFE","VANILLE","NATA","YOGURT")

# Crear una función que verifica si alguna de las palabras está presente en el texto
verificar_palabras <- function(texto, palabras) {
  sapply(palabras, function(palabra) grepl(palabra, texto))
}
# Identificar las filas que contienen alguna de las palabras a eliminar
filas_a_eliminar <- apply(df_nuevo, 1, function(row) any(verificar_palabras(row["PRODUCT_NAME"], palabras_a_eliminar)))

# Eliminar las filas identificadas del dataframe original
df_nuevo1 <- df_nuevo[!filas_a_eliminar, ]
#df_nuevo2 <- df_nuevo1[,-1]

#Elimino los faltantes
df_nuevo1 <- df_nuevo1[complete.cases(df_nuevo1), ]

```

```{r}
df_soja <- subset(df_nuevo1, grepl("soja", PRODUCT_NAME, ignore.case = TRUE)) ## Registros que contienen la palabra "soja"
df_seitan <- subset(df_nuevo1, grepl("seitan", PRODUCT_NAME, ignore.case = TRUE)) ## Registros que contienen la palabra "seitan"
df_tofu <- subset(df_nuevo1, grepl("tofu", PRODUCT_NAME, ignore.case = TRUE)) ## Registros que contienen la palabra "tofu"
df_tofu <- na.omit(df_tofu)

```


```{r}
# Definir la función para eliminar valores atípicos basados en desviación estándar
remove_outliers <- function(data, column, sd_threshold = 2) {
  data[abs(scale(data[[column]])) < sd_threshold, ]
}
# Eliminar valores atípicos en columna1 utilizando desviación estándar
df_soja <- remove_outliers(df_soja, "PROTEINS_100G")
df_soja <- remove_outliers(df_soja, "CARBOHYDRATES_100G")
df_soja <- remove_outliers(df_soja, "FAT_100G")
#df_soja <- remove_outliers(df_soja, "SUGARS_100G")

# Eliminar valores atípicos en columna1 utilizando desviación estándar
df_seitan <- remove_outliers(df_seitan, "PROTEINS_100G")
df_seitan <- remove_outliers(df_seitan, "CARBOHYDRATES_100G")
df_seitan <- remove_outliers(df_seitan, "FAT_100G")
#df_seitan <- remove_outliers(df_seitan, "SUGARS_100G")

# Eliminar valores atípicos en columna1 utilizando desviación estándar
df_tofu <- remove_outliers(df_tofu, "PROTEINS_100G")
df_tofu <- remove_outliers(df_tofu, "CARBOHYDRATES_100G")
df_tofu <- remove_outliers(df_tofu, "FAT_100G")
#df_tofu <- remove_outliers(df_tofu, "SUGARS_100G")
```
```{r}
clara_clusters <- clara(x = scale(df_soja[,-1]), k = 3, metric = "manhattan", stand = TRUE,
                        samples = 60, pamLike = TRUE)
clara_clusters$sample
clara_clusters$medoids
clara_clusters$i.med
clara_clusters$clustering
table(clara_clusters$clustering)
fviz_cluster(object = clara_clusters, ellipse.type = "t", geom = "point",
             pointsize = 1.5) +  theme_bw() +
  labs(title = "Resultados clustering CLARA") +
  theme(legend.position = "none")
```
```{r}
clara_clusters <- clara(x = scale(df_seitan[,-1]), k = 3, metric = "manhattan", stand = TRUE,
                        samples = 60, pamLike = TRUE)
clara_clusters$sample
clara_clusters$medoids
clara_clusters$i.med
clara_clusters$clustering
table(clara_clusters$clustering)
fviz_cluster(object = clara_clusters, ellipse.type = "t", geom = "point",
             pointsize = 1.5) +  theme_bw() +
  labs(title = "Resultados clustering CLARA") +
  theme(legend.position = "none")
```

```{r}
df_tofu <- na.omit(df_tofu)


clara_clusters <- clara(x = scale(df_tofu[,-1]), k = 4, metric = "manhattan", stand = TRUE,
                        samples = 60, pamLike = TRUE)
clara_clusters$sample
clara_clusters$medoids
clara_clusters$i.med
clara_clusters$clustering
table(clara_clusters$clustering)
fviz_cluster(object = clara_clusters, ellipse.type = "t", geom = "point",
             pointsize = 1.5) +  theme_bw() +
  labs(title = "Resultados clustering CLARA") +
  theme(legend.position = "none")
```

