---
title: "Untitled"
author: "Ricardo Rodriguez"
date: "2023-08-25"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(jsonlite)
knitr::opts_chunk$set(echo = TRUE)
```



```{r, echo = FALSE, warning = FALSE}


# Normalizar una columna con los valores máximos y mínimos
normalize_column <- function(column, max_value, min_value) {
  return((column - min_value) / (max_value - min_value))
}

# Buscar cluster mas cercano a producto
encontrar_cercano_cluster <- function(TIPO_PRODUCTO, DT_ENERGY_100G, DT_FAT_100G, DT_CARBOHYDRATES_100G, DT_PROTEINS_100G) {
  
  if (!(TIPO_PRODUCTO %in% c("soja", "tofu", "seitan"))) {
    stop("Tipo de producto no válido.")
  }
  
  # Leer las descripciones de los clústeres desde un archivo JSON
  descripciones_clusters <- fromJSON("descripciones_clusters.json")
  
  if(TIPO_PRODUCTO == "soja") {
    max_min <- fromJSON("max_min_soja.json")
    centroides <- fromJSON("centroides_soja.json")
  }
  if(TIPO_PRODUCTO == "tofu") {
    max_min <- fromJSON("max_min_tofu.json")
    centroides <- fromJSON("centroides_tofu.json")
  }
  if(TIPO_PRODUCTO == "seitan") {
    max_min <- fromJSON("max_min.json")
    centroides <- fromJSON("centroides_seitan.json")
  }

  nuevo_producto_normalizado <- data.frame(
    ENERGY_100G =  normalize_column(DT_ENERGY_100G, max_min$ENERGY_100G$MAX, max_min$ENERGY_100G$MIN),
    FAT_100G = normalize_column(DT_FAT_100G, max_min$FAT_100G$MAX, max_min$FAT_100G$MIN),
    CARBOHYDRATES_100G = normalize_column(DT_CARBOHYDRATES_100G, max_min$CARBOHYDRATES_100G$MAX, max_min$CARBOHYDRATES_100G$MIN),
    PROTEINS_100G = normalize_column(DT_PROTEINS_100G, max_min$PROTEINS_100G$MAX, max_min$PROTEINS_100G$MIN)
  )
    
  # Asegurarse de que las columnas del nuevo producto y los centroides coinciden
  if (!all(names(nuevo_producto_normalizado) %in% names(centroides))) {
    stop("Las columnas del nuevo producto y los centroides deben coincidir.")
  }
  
  # Calcula las distancias euclidianas entre el nuevo producto y cada centroide
  distancias <- apply(centroides, 1, function(centroide) {
    suma_cuadrados <- sum((nuevo_producto_normalizado - centroide)^2)
    sqrt(suma_cuadrados)
  })
  
  # Encuentra el índice del centroide más cercano
  indice_centroide_cercano <- which.min(distancias)
  
  # Identificar el color y la descripción del cluster
  color_descripcion <- descripciones_clusters[[TIPO_PRODUCTO]][indice_centroide_cercano]
  
  # Devolver el mensaje y las características del centroide
  list(
    color = names(color_descripcion),
    descripcion = color_descripcion[as.character(names(color_descripcion))][1]
  )
  
}
```


```{r, echo = FALSE, warning = FALSE}
# Determina a qué clúster pertenece el nuevo producto
# INPUT: TIPO_PRODUCTO, ENERGY_100G, FAT_100G, CARBOHYDRATES_100G, PROTEINS_100G
resultado <- encontrar_cercano_cluster("soja", 515, 7.060000, 11.428571, 14.084507)
print(resultado$color)
print(resultado$descripcion)
```